### ISSUE TITLE
BM issue

### ISSUE THREAD

**Issue by Karjala22** [njankowski/dftools#1] opened 2021-02-11 18:42 UTC
Hi Nicholas,

I have a BM that seems to fail the RLE1 compression (due to row offset vs decompressed list mismatch). The 32-bit header payload is  _42 4D 20 1E 80 00 80 00 80 00 80 00 3E 07 **01** 00 59 0A_  so compression is RLE1 .

It's a 128x128 texture, I can decompress it without issue using https://df-21.net/downloads/uploads/600036564/bmpdf.zip

**DF2 WIRES2.BM /m** (in dosbox)

[WIRES2.zip](https://github.com/njankowski/dftools/files/5967576/WIRES2.zip)

Do you know why there is a mismatch? Is there any issue with the decompression algorithm or is the texture somehow corrupt? And where could one get detailed format specs (Ex: header info). 

Are you in TFE discord by any chance? If so may I contact you there? Otherwise there is a DF-21.net discord as well --> https://discord.gg/6T9NvMh2MC

Thanks!
Karjala

**Comment by njankowski** [comment] 2021-02-12 01:09
This is definitely an issue with how the file is compressed.

It does not match the DF specifications:
https://github.com/njankowski/dftools/tree/master/doc/dfspecs

There are some malformed control bytes that cause the column to expand beyond its expected size of 128 pixels at multiple column offsets.
The first appearance of the issue is when decompressing the column at absolute offset 813.

I am not sure how DF2 manages to solve this issue, but after some educated guesswork, I think it is skipping these malformed bytes.

A possible fix is in:
https://github.com/njankowski/dftools/tree/issue-1
https://github.com/njankowski/dftools/commit/8b2299c3da56fd0d69a80f2158363248c46808c7

Result:
![WIRES2](https://user-images.githubusercontent.com/11827629/107718863-dc379a80-6ca4-11eb-9424-1a9c2c023d9e.png)

**Comment by Karjala22** [comment] 2021-02-12 02:04
Thank you Nicholas!

I can confirm that's a fix for Wires. Before the decompressed value was about 18000 which is more than a 128**2=16384 square texture.

By the way I think I see a similar issue with SLIGHT3.BM (64*2048 = 131072) but decompressed is showing 169472 and a few others. I am working on an asset_parser/organizer for DF-21.net . Here are a few more examples (I also may have seen some magic # mismatch for WAXes - separate thread).

[badbm.zip](https://github.com/njankowski/dftools/files/5969343/badbm.zip)


Thanks!
Karjala

**Comment by njankowski** [comment] 2021-02-14 00:38
Thanks for the samples!

I updated the branch with a new solution that seems to work with these four broken files.

d04f70bf91d2e41c144d99468b90cca14611d552

Did these files come with any readmes or other information from the authors that tell what tool was used to compress the image?

I think knowing what tool was used might be the only way to determine precisely what the bug is and how to account for it.

Also for your reference, DF2 maps colors differently than bmtool.

bmtool outputs colors as they are seen in DOSBox, so there will be detectable colors differences between the two tools.

If you use the --compatible option I added as a test in the above commit, bmtool will map color like DF2 which should create identical images.

**Comment by Karjala22** [comment] 2021-02-14 02:21
Hi Nicholas,

These particular BMs come from custom GOBs, I am putting them through SECBASE.PAL by default (eventually I want to add a parser that extracts the right PAL). The ones I sent just now are from Dark Tide IV. https://df-21.net/downloads/missions.php?
viewid=1745302688 

Good news, the latest commit (with the new rle1 version) has lowered the list of failed BMs down by 2/3. Here is a list of the last 7 BMs. Two of them, COSMOS.BM and SIGN18.BM can be converted by DF2 but not with the compatibility flag. The rest don't convert at all, so they just may be bugged (SCRBARS in particular is corrupt it seems). 

[badbm2.zip](https://github.com/njankowski/dftools/files/5976879/badbm2.zip)

GOB Sources:
https://df-21.net/downloads/missions.php?viewid=1212146665
SCRBARS.BM

(Honestly this level is a mess in general - the cotalogue payload is corrupt)
https://df-21.net/downloads/missions.php?viewid=852970793
BLUEFLARE.BM 

https://df-21.net/downloads/missions.php?viewid=779742578
COSMOS.BM

https://df-21.net/downloads/missions.php?viewid=1745302688  
VERTSIG3.BM
VERTSIG5.BM
VERTSIG6.BM
SIGN18.BM

By the way I am available to test at any time . Do you have a a preferred method of communication, or would you like to do it in github? 

Thanks!
Karjala

**Comment by njankowski** [comment] 2021-02-16 01:07
It seems that a control byte of 128 is not allowed in the RLE1 compression scheme, which goes against the unofficial specifications.

With some code changes, I have been able to open all of the above BM files.

The changes are currently on master branch.

**Questions**

> BLUEFLARE.BM from BGM

Do you mean "BLUFLARE.BM" from DTide4?

That is the only GOB I could find with a BM with a similar name.

**Other Points**

> can be converted by DF2 but not with the compatibility flag

This flag is only for producing identical color output to DF2, so I think there was a misunderstanding.

I was using it to compare the pixel output to DF2.

Otherwise, if DOSBox accurate colors are desired, do not use that flag.

> SCRBARS in particular is corrupt it seems

It has several header fields written as big endian instead of little endian.

Swapping the order of these fields allowed the file to be converted.

master branch should now handle this.

> (Honestly this level is a mess in general - the cotalogue payload is corrupt)

I was able to extract this GOB with some tweaks to the gob.read() function.

Specifically, ignoring if a filename is missing a null terminator.

"LIGHTSABER.WA" duplicated twice, no null terminator (probably meant to be a WAX).
"LIGHTSABER.BM" no null terminator.

master branch should now handle this.

> By the way I am available to test at any time .

Great to hear!

These samples you pointed out have already been really useful, and thanks for testing the new code.

I really only tested the original RLE1 code on BUYIT.BM from the DF demo files, which was missing the problem control bytes.

> Do you have a a preferred method of communication, or would you like to do it in github?

At the moment, GitHub, just so that we can have a record of our problem solving steps.

**Comment by Karjala22** [comment] 2021-02-17 05:22
Hi,

You are right, the BLUFLARE.BM is from DTIDE 4.

Unfortunately this latest commit broke a lot more BMs. For example **VATCRUD.BM** when sends a width of **16384** and a height of **32768** (it's really a 128x64 texture) to imaging.py. When it tries to load the data array of size (128x64=8192) it fails at  **data[row*width+col]** when **row*width+col** goes past 8192 and blows up.

` pixels[col, row] = (rgb_palette[data[row * width + col]][0]` <-- throws index out of range

![image](https://user-images.githubusercontent.com/78927981/108156593-f7444900-70ae-11eb-8275-76a51787aa20.png)

It looks like when it gets here in bm.py it is converting 128 and 64 to 32768 and 16384

```
            bm.x = ((bm.x & 0xFF00) >> 8) | ((bm.x & 0x00FF) << 8)
            bm.y = ((bm.y & 0xFF00) >> 8) | ((bm.y & 0x00FF) << 8)

```
 _bm.x = ((bm.x & 0xFF00) >> 8) | ((bm.x & 0x00FF) << 8)_  # This becomes **bm.x =(0>>8 ) | (128 << 8)**   or **0 | 32768**

It is jumping inside this conditional because the data size is 0.  If I comment that section that  BMs load fine (but not others).

Here is the texture in partuclar. 

[bmbug.zip](https://github.com/njankowski/dftools/files/5993323/bmbug.zip)

I think it would be useful to have a test case. I put the BMs in a rar here --> https://df-21.net/downloads/conf_files/BM.rar

And here is the test case I used, just change the paths to the extracted BMs from the rar. 

```
from formats import bm, pal
import os
import traceback

PATH_TO_BMS = "F:/DF Custom Map/assets/GOB/BM"
rgb_palette = pal.load_internal_compat("SECBASE")
failed = []

for bmfile in os.listdir(PATH_TO_BMS):
    if bmfile.lower().endswith('bm'):
        image = os.path.join(PATH_TO_BMS, bmfile)
        print ("Parsing {0}... ".format(image))
        try:
            converted_images = bm.to_images(bm.read(image), rgb_palette)
            for i in range(len(converted_images)):
                if len(converted_images) == 1:
                    converted_images[i].save(f'{bmfile}.png')
                else:
                    converted_images[i].save(f'{bmfile}({str(i)}).png')
        except:
            failed.append("Failed to convert {0} due to [{1}]".format(image, traceback.format_exc()))

for msg in failed:
    print(msg)
```

**Comment by njankowski** [comment] 2021-02-17 20:09
I apologize for my haste in trying to fix these issues.

This time I ran the converter through:

- The comprehensive BM.rar package above
- Demo BMs
- Stock BMs
- bgm
- cond-red
- dt1se
- dtide4
- Any problem BMs mentioned specifically above

The issue with the swapping condition and VATCRUD.BM is that the BM has zero for its data size field, so we cannot rely on the comparison of the resolution to the data size.

I added in one more condition to avoid swapping if the data size field is zero.

dd28a0e87863e74329d8a087997066f94160e9ce

> Here is the texture in partuclar.

I looked within bmbug.zip at that PNG file.

I'm not sure if it was converted with DF2 or with bmtool with the '-c' option, but I wanted to be clear that there will be pixel color differences compared to bmtool _without_ the '-c' option.

If you want DOSBox accurate colors, do _not_ use the '-c' option.

DF2 does not produce DOSBox accurate colors.

If you want to compare DF2 output to bmtool, then the '-c' option will make bmtool output colors like DF2 so you can compare the images more directly.

I wanted to illustrate those minute differences.

Any highlighted magenta pixel is where DF2 and bmtool (without '-c') will differ in color (they differ _a lot_)

![vatcrud-df2-vs-bmtool](https://user-images.githubusercontent.com/11827629/108265036-41244200-7136-11eb-9cb5-25adfb55e982.png)

These differences can be almost impossible to see on most screens, so comparing with an image editor is best.

In general, bmtool images will be brighter overall than DF2 images.

> I think it would be useful to have a test case.

Definitely.

I think once the code itself becomes more solid, I will spend some time on creating a test suite for this repository with these bad or tricky BM examples included.

Also, this issue you brought up with RLE1 actually solved a major roadblock with _compressing_ images with RLE1 too.

That gives me some motivation to continue working on the PNG to BM (and other) logic.

Thanks again!

**Comment by Karjala22** [comment] 2021-02-18 08:43
Thank you Nicholas, I can confirm this is the fix, and everything looks solid. 

I don't see any other issues with this so this can be closed. 

As an aside, not issue related, I am going to see if I can create the BMP-->DLT /ANIM -->LFDs archive version (I assume it wasn't trivial?). 

I have an automated briefing/objective creator (cleaning up ancient maps) prior to TFE release.

```
objectives = ["Get on the Executor and kill Darth Vader",
              "After that, find where he is hiding princess Leia and throw her out of the airlock",
              "Send the emperor to live on a farm upstate",
              "Ensure Jar Jar Binks becomes the new Emperor by giving him a cool lightsaber and make sure he is converted to the Dark Side."]
title= "Assassinate  Leia:   The Danishes must go!"
background = "It's a well known fact that Leia is the root of evil in this galaxy. " + \
             "She is responsible for kicking innocent Ewoks in the shins. Taking her out will bring order to the galaxy.  "
mission = "The princess is hiding in her fortress on the Death Star. Her exact location is level 5 in Detention Block AA-23." + \
          " She is guarded by multiple stormtroopers who need to be blown up to smithereens. When you reach her take her to a farm upstate"

create_mission_briefing("karmap",title, background, mission, objectives)
```

![image](https://user-images.githubusercontent.com/78927981/108328415-9134f000-719a-11eb-92e4-3f6de2e85538.png)

At the moment I have auto-alignment (in 198px briefing widths) PIL BMP creation of both Briefing and Objectives overlays.

![image](https://user-images.githubusercontent.com/78927981/108328708-ea048880-719a-11eb-8eae-605a187e9411.png)
![image](https://user-images.githubusercontent.com/78927981/108328672-dd803000-719a-11eb-87d1-12dd63ce264a.png)

I can use 2DF ` 2df /d karmap.bmp SECBASE.DLT brf-jan.plt` and then using conman, stick it into LFD. 

Anyway, thanks again for all your help! You really saved DF-21 a lot of time. 

Thanks,
Karjala

**Comment by njankowski** [comment] 2021-02-18 20:10
> I don't see any other issues with this so this can be closed.

Great!

Thanks again for testing and reporting these samples.

> I am going to see if I can create the BMP-->DLT /ANIM -->LFDs archive version (I assume it wasn't trivial?).

It shouldn't be too hard, but I haven't attempted that specific path.

The DLT is probably the toughest of the bunch, with the ANIM and LFD only being containers.

> I have an automated briefing/objective creator (cleaning up ancient maps) prior to TFE release.

It looks really slick!

I'm happy to see so many people working on this game.

> TFE release

This RLE bug is also applicable to that project, so you may want to file an issue there too.

Since Lucius is deep into the RE territory, he should be able to confirm this against the game's disassembly.

I think we've all been relying on the unofficial specifications to some degree.

> Anyway, thanks again for all your help! You really saved DF-21 a lot of time.

Good to hear!

I actually didn't notice you were a DF-21 admin until this moment.

I'll consider popping into the Discord, since it sounds like we have quite a bit of development going on.

</br>

Closing the issue because it was fixed by commits:

Final Attempt (Correct Solution):
0d19741f7ce6d3429a3a02475c14897ba1a375c4

Second Attempt:
d04f70bf91d2e41c144d99468b90cca14611d552

First Attempt:
26c74c31c904a549f2566fc10eca04a8db2e09e9
8b2299c3da56fd0d69a80f2158363248c46808c7


Thanks again!

**Closed as completed by njankowski** 2021-02-18 20:10 UTC
